---
- hosts: localhost
  connection: local
  become: true

  tasks:
  - name: install packages
    package:
      name: 
        - i3
        - vim
        - neovim
        - feh
        - stow
        - alacritty
        - zsh
	- curl


#oh my zsh installation requires to do:
# sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" 
#


#p10k theme for ohmyzsh use manual install not the oh myzsh one and remeber to restart terminal after
#git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ~/powerlevel10k
#echo 'source ~/powerlevel10k/powerlevel10k.zsh-theme' >>~/.zshrc
