---
- hosts: localhost
  connection: local
  become: true

  tasks:
  - name: install packages
    package:
      name: 
        - i3
        - vim
        - neovim
        - feh
        - stow
        - alacritty
        - zsh
	- curl
	- wget
	- build-essential


#oh my zsh installation requires to do:
# sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" 
#




