---
- hosts: localhost
  connection: local
  become: true

  tasks:
  - name: install packages
    package:
      name: 
        - i3
        - vim
        - neovim
        - feh
        - stow
        - alacritty
        - zsh
        - tmux
        - wget
        - curl
  - name: Install ohmyzsh
    ansible.builtin.git:
      repo: https://github.com/ohmyzsh/ohmyzsh.git
      dest: ~/.oh-my-zsh
      depth: 1
